AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test

  A test application to demo AWS Serverless Application Model
Resources:
  PostsTable:
    Type: AWS::Serverless::SimpleTable

  Greeter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
      - x86_64

  HelloWorldGraphQLApi:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      SchemaUri: ./gql/schema.graphql
      Auth:
        Type: API_KEY
      ApiKeys:
        MyApiKey:
          Description: The API Key used for private endpoints
      DataSources:
        DynamoDb:
          Posts:
            TableName: !Ref PostsTable
            TableArn: !GetAtt PostsTable.Arn
        Lambda:
          Greeter:
            FunctionArn: !GetAtt Greeter.Arn
      Functions:
        preprocessPostItem:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: NONE
          CodeUri: ./gql/preprocessPostItem.js
        createPostItem:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: Posts
          CodeUri: ./gql/createPostItem.js
        getPostFromTable:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: Posts
          CodeUri: ./gql/getPostFromTable.js
        greet:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: Greeter
          CodeUri: ./gql/greet.js
      Resolvers:
        Mutation:
          addPost:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - preprocessPostItem
            - createPostItem
        Query:
          getPost:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - getPostFromTable
          sayHello:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - greet
          sayGoodbye:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - greet


Outputs:
  HelloWorldGraphQLApi:
    Description: HelloWorldGraphQLApi endpoint URL for Prod environment
    Value: !GetAtt HelloWorldGraphQLApi.GraphQLUrl
  HelloWorldGraphQLApiMyApiKey:
    Description: API Key for HelloWorldGraphQLApi
    Value: !GetAtt HelloWorldGraphQLApiMyApiKey.ApiKey

Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true
